<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Writes the toll plazas and toll matrix in the database to toll-data.js,
 * the file the Plan a Trip page reads (window.SMARTTOLL_DATA).
 *
 * Run it again whenever plazas, coordinates or rates change:
 *
 *   php artisan trb:export-js
 *   php artisan trb:export-js "E:/path/to/mockup/toll-data.js"
 *
 * Each expressways row becomes one "toll system". The key (NLEX, SLEX...)
 * is taken from the brackets in expressway_name, e.g.
 * "South Luzon Expressway (SLEX)" -> SLEX. It must match the keys in
 * planner-core.js (ROAD_RULES), which map road names from OSRM to a system.
 */
class TrbExportJsCommand extends Command
{
    protected $signature = 'trb:export-js {path? : Where to write the file (default: storage/app/trb/toll-data.js)}';
    protected $description = 'Export toll plazas and the toll matrix to toll-data.js for the trip planner page';

    /** key => [label shown to the motorist, RFID network that collects there] */
    private const SYSTEMS = [
        'NLEX'    => ['NLEX / SCTEX', 'Easytrip'],
        'TPLEX'   => ['TPLEX', 'Autosweep'],
        'SLEX'    => ['Skyway / SLEX / MCX', 'Autosweep'],
        'STAR'    => ['STAR Tollway', 'Autosweep'],
        'CALAX'   => ['CALAX', 'Easytrip'],
        'CAVITEX' => ['CAVITEX / C5 Link', 'Easytrip'],
    ];

    public function handle(): int
    {
        $path = $this->argument('path') ?: storage_path('app/trb/toll-data.js');

        // vehicle_classifications.classification_id -> class number (1, 2, 3)
        $classNumber = [];
        foreach (DB::table('vehicle_classifications')->get() as $c) {
            if (preg_match('/(\d)/', $c->class_name, $m)) {
                $classNumber[$c->classification_id] = $m[1];
            }
        }
        if (!$classNumber) {
            $this->error('No vehicle classifications found (expected class_name like "Class 1").');
            return self::FAILURE;
        }

        $systems = [];
        $plazas = [];
        $systemOfPlaza = [];
        $missingCoords = [];

        foreach (DB::table('expressways')->orderBy('expressway_id')->get() as $ex) {
            $rows = DB::table('toll_plazas')->where('expressway_id', $ex->expressway_id)->orderBy('plaza_id')->get();
            if ($rows->isEmpty()) {
                continue;   // expressway registered but nothing imported yet
            }

            $key = $this->systemKey($ex->expressway_name);
            [$label, $network] = self::SYSTEMS[$key] ?? [$ex->expressway_name, null];
            if (!isset(self::SYSTEMS[$key])) {
                $this->warn("\"{$ex->expressway_name}\" exported as system \"{$key}\", which the planner has no road-name rule for yet.");
            }
            $systems[$key] = ['label' => $label, 'network' => $network];

            foreach ($rows as $p) {
                $lat = (float) $p->latitude;
                $lng = (float) $p->longitude;
                if ($lat == 0.0 && $lng == 0.0) {
                    $missingCoords[] = "{$p->plaza_name} ({$key})";
                }
                $plazas[] = ['id' => (int) $p->plaza_id, 'system' => $key, 'name' => $p->plaza_name, 'lat' => $lat, 'lng' => $lng];
                $systemOfPlaza[$p->plaza_id] = $key;
            }
        }

        if (!$plazas) {
            $this->error('No toll plazas found. Run trb:seed-plazas and trb:import first.');
            return self::FAILURE;
        }

        $rates = [];
        $rateCount = 0;
        foreach (DB::table('toll_matrix')->orderBy('matrix_id')->get() as $r) {
            $class = $classNumber[$r->classification_id] ?? null;
            if ($class === null || !isset($systemOfPlaza[$r->entry_plaza_id], $systemOfPlaza[$r->exit_plaza_id])) {
                continue;
            }
            $rates[$class]["{$r->entry_plaza_id}|{$r->exit_plaza_id}"] = (float) $r->rate;
            $rateCount++;
        }
        ksort($rates);

        $data = [
            'generated' => date('Y-m-d'),
            'coordinateSource' => 'SmartToll database (toll_plazas.latitude / longitude)',
            'systems' => $systems,
            'plazas' => $plazas,
            'rates' => $rates,
        ];

        $js = "/* SmartToll toll data — generated by `php artisan trb:export-js` on " . date('Y-m-d H:i') . ".\n"
            . " * Do not edit by hand: change the data in the admin screens / database and export again.\n */\n"
            . 'window.SMARTTOLL_DATA = ' . json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . ";\n";

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0775, true);
        }
        file_put_contents($path, $js);

        $this->info('Wrote ' . count($plazas) . " plazas, {$rateCount} rates and " . count($systems) . " toll systems to {$path}");

        if ($missingCoords) {
            $this->warn(count($missingCoords) . ' plaza(s) still have coordinates 0,0 and cannot be matched to a route:');
            foreach ($missingCoords as $name) {
                $this->line("  - {$name}");
            }
            $this->line('Run trb:geocode, or set them by hand, then export again.');
        }

        return self::SUCCESS;
    }

    /** "South Luzon Expressway (SLEX)" -> SLEX ; "STAR Tollway" -> STAR */
    private function systemKey(string $name): string
    {
        if (preg_match('/\(([A-Za-z0-9\-]+)\)/', $name, $m)) {
            return strtoupper($m[1]);
        }
        foreach (array_keys(self::SYSTEMS) as $key) {
            if (stripos($name, $key) !== false) {
                return $key;
            }
        }
        return strtoupper(preg_replace('/[^A-Za-z0-9]+/', '_', trim($name)));
    }
}
